export interface TableStyles {
  fontFamily: string;
  fontSize: number;
  textColor: string;
  backgroundColor: string;
  headerColor: string;
  borderColor: string;
  borderStyle: 'solid' | 'dashed' | 'dotted' | 'none';
  borderWidth: number;
  cellPadding: number;
  textAlignment: 'left' | 'center' | 'right';
  stripedRows: boolean;
  hoverEffects: boolean;
  headerStyling: boolean;
  roundedCorners: boolean;
}

export interface TableData {
  headers: string[];
  rows: string[][];
}

export interface ExportSettings {
  quality: 'high' | 'medium' | 'low';
  background: 'transparent' | 'white' | 'custom';
  customBackground?: string;
}

export const DEFAULT_STYLES: TableStyles = {
  fontFamily: 'Inter',
  fontSize: 14,
  textColor: '#1F2937',
  backgroundColor: '#FFFFFF',
  headerColor: '#F9FAFB',
  borderColor: '#E5E7EB',
  borderStyle: 'solid',
  borderWidth: 1,
  cellPadding: 12,
  textAlignment: 'left',
  stripedRows: true,
  hoverEffects: false,
  headerStyling: true,
  roundedCorners: false,
};

export const PRESET_THEMES = {
  default: DEFAULT_STYLES,
  minimal: {
    ...DEFAULT_STYLES,
    borderStyle: 'none' as const,
    stripedRows: false,
    headerStyling: false,
    backgroundColor: '#FFFFFF',
    headerColor: '#FFFFFF',
  },
  dark: {
    ...DEFAULT_STYLES,
    backgroundColor: '#1F2937',
    headerColor: '#374151',
    textColor: '#F9FAFB',
    borderColor: '#4B5563',
  },
  corporate: {
    ...DEFAULT_STYLES,
    fontFamily: 'Arial',
    headerColor: '#F3F4F6',
    borderColor: '#D1D5DB',
    stripedRows: false,
  },
  ocean: {
    ...DEFAULT_STYLES,
    textColor: '#1E293B',
    backgroundColor: '#FFFFFF',
    headerColor: '#E0F2FE',
    borderColor: '#0891B2',
    borderWidth: 1,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  forest: {
    ...DEFAULT_STYLES,
    textColor: '#1F2937',
    backgroundColor: '#FFFFFF',
    headerColor: '#DCFCE7',
    borderColor: '#16A34A',
    cellPadding: 14,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  sunset: {
    ...DEFAULT_STYLES,
    textColor: '#7C2D12',
    backgroundColor: '#FFFBEB',
    headerColor: '#FED7AA',
    borderColor: '#EA580C',
    borderWidth: 2,
    stripedRows: true,
    hoverEffects: true,
  },
  lavender: {
    ...DEFAULT_STYLES,
    textColor: '#4C1D95',
    backgroundColor: '#FAFAFF',
    headerColor: '#E9D5FF',
    borderColor: '#7C3AED',
    cellPadding: 16,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  newspaper: {
    ...DEFAULT_STYLES,
    fontFamily: 'Georgia',
    fontSize: 12,
    textColor: '#000000',
    backgroundColor: '#FFFFFF',
    headerColor: '#F5F5F5',
    borderColor: '#000000',
    borderWidth: 2,
    cellPadding: 8,
    stripedRows: false,
    hoverEffects: false,
  },
  soft_pink: {
    ...DEFAULT_STYLES,
    textColor: '#881337',
    backgroundColor: '#FFF7ED',
    headerColor: '#FECACA',
    borderColor: '#F43F5E',
    cellPadding: 14,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  mint: {
    ...DEFAULT_STYLES,
    textColor: '#064E3B',
    backgroundColor: '#F0FDF4',
    headerColor: '#A7F3D0',
    borderColor: '#10B981',
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  steel: {
    ...DEFAULT_STYLES,
    fontSize: 13,
    textColor: '#374151',
    backgroundColor: '#F9FAFB',
    headerColor: '#E5E7EB',
    borderColor: '#6B7280',
    cellPadding: 11,
    stripedRows: true,
    hoverEffects: true,
  },
  royal: {
    ...DEFAULT_STYLES,
    textColor: '#1E1B4B',
    backgroundColor: '#FFFFFF',
    headerColor: '#C7D2FE',
    borderColor: '#4338CA',
    borderWidth: 2,
    cellPadding: 15,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  cream: {
    ...DEFAULT_STYLES,
    fontFamily: 'Georgia',
    textColor: '#451A03',
    backgroundColor: '#FFFBEB',
    headerColor: '#FED7AA',
    borderColor: '#92400E',
    cellPadding: 14,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  arctic: {
    ...DEFAULT_STYLES,
    fontSize: 13,
    textColor: '#0F172A',
    backgroundColor: '#F8FAFC',
    headerColor: '#E2E8F0',
    borderColor: '#475569',
    stripedRows: true,
    hoverEffects: true,
  },
  crimson: {
    ...DEFAULT_STYLES,
    textColor: '#7F1D1D',
    backgroundColor: '#FFFFFF',
    headerColor: '#FECACA',
    borderColor: '#DC2626',
    borderWidth: 2,
    stripedRows: false,
    hoverEffects: true,
  },
  sage: {
    ...DEFAULT_STYLES,
    textColor: '#365314',
    backgroundColor: '#F7FEE7',
    headerColor: '#BEF264',
    borderColor: '#65A30D',
    cellPadding: 13,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  midnight: {
    ...DEFAULT_STYLES,
    textColor: '#F1F5F9',
    backgroundColor: '#1E293B',
    headerColor: '#334155',
    borderColor: '#64748B',
    cellPadding: 14,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  gold: {
    ...DEFAULT_STYLES,
    textColor: '#78350F',
    backgroundColor: '#FFFBEB',
    headerColor: '#FDE68A',
    borderColor: '#D97706',
    borderWidth: 2,
    cellPadding: 15,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  emerald: {
    ...DEFAULT_STYLES,
    textColor: '#064E3B',
    backgroundColor: '#ECFDF5',
    headerColor: '#6EE7B7',
    borderColor: '#059669',
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  rose: {
    ...DEFAULT_STYLES,
    textColor: '#9F1239',
    backgroundColor: '#FFF1F2',
    headerColor: '#FECDD3',
    borderColor: '#E11D48',
    cellPadding: 13,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  amber: {
    ...DEFAULT_STYLES,
    textColor: '#92400E',
    backgroundColor: '#FFFBEB',
    headerColor: '#FCD34D',
    borderColor: '#F59E0B',
    borderWidth: 2,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: false,
  },
  slate: {
    ...DEFAULT_STYLES,
    fontSize: 13,
    textColor: '#1E293B',
    backgroundColor: '#F8FAFC',
    headerColor: '#CBD5E1',
    borderColor: '#64748B',
    cellPadding: 10,
    stripedRows: true,
    hoverEffects: true,
  },
  // NEW THEMES
  monochrome: {
    ...DEFAULT_STYLES,
    textColor: '#262626',
    backgroundColor: '#FAFAFA',
    headerColor: '#E5E5E5',
    borderColor: '#737373',
    borderStyle: 'solid',
    cellPadding: 12,
    stripedRows: true,
    hoverEffects: false,
    roundedCorners: false,
  },
  neon: {
    ...DEFAULT_STYLES,
    textColor: '#0d0208',
    backgroundColor: '#FFFFFF',
    headerColor: '#00ff41',
    borderColor: '#003B00',
    borderWidth: 2,
    cellPadding: 15,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  pastel: {
    ...DEFAULT_STYLES,
    textColor: '#6b7280',
    backgroundColor: '#FFFFFF',
    headerColor: '#FBCFE8',
    borderColor: '#FCA5A5',
    borderWidth: 1,
    cellPadding: 14,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  nautical: {
    ...DEFAULT_STYLES,
    textColor: '#0F172A',
    backgroundColor: '#F0F9FF',
    headerColor: '#BAE6FD',
    borderColor: '#0369A1',
    borderWidth: 2,
    cellPadding: 13,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: false,
  },
  desert: {
    ...DEFAULT_STYLES,
    textColor: '#7C2D12',
    backgroundColor: '#FEFCE8',
    headerColor: '#FEF08A',
    borderColor: '#CA8A04',
    borderWidth: 1,
    cellPadding: 12,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  // ADDITIONAL NEW THEMES
  cyberpunk: {
    ...DEFAULT_STYLES,
    textColor: '#ECFDF5',
    backgroundColor: '#171717',
    headerColor: '#7E22CE',
    borderColor: '#F472B6',
    borderWidth: 2,
    cellPadding: 14,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  winter: {
    ...DEFAULT_STYLES,
    textColor: '#1E293B',
    backgroundColor: '#F9FAFB',
    headerColor: '#DBEAFE',
    borderColor: '#93C5FD',
    borderWidth: 1,
    cellPadding: 12,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: false,
  },
  autumn: {
    ...DEFAULT_STYLES,
    textColor: '#713F12',
    backgroundColor: '#FFFBEB',
    headerColor: '#FDE68A',
    borderColor: '#D97706',
    borderWidth: 1,
    cellPadding: 14,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  cherry: {
    ...DEFAULT_STYLES,
    textColor: '#9F1239',
    backgroundColor: '#FFF1F2',
    headerColor: '#FDA4AF',
    borderColor: '#E11D48',
    borderWidth: 1,
    cellPadding: 15,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  coffee: {
    ...DEFAULT_STYLES,
    fontFamily: 'Georgia',
    textColor: '#44403C',
    backgroundColor: '#FAFAF9',
    headerColor: '#E7E5E4',
    borderColor: '#78716C',
    borderWidth: 1,
    cellPadding: 12,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: false,
  },
  vintage: {
    ...DEFAULT_STYLES,
    fontFamily: 'Georgia',
    fontSize: 13,
    textColor: '#57534E',
    backgroundColor: '#FEFCE8',
    headerColor: '#FEF9C3',
    borderColor: '#A16207',
    borderWidth: 1,
    borderStyle: 'dashed',
    cellPadding: 14,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: false,
  },
  tech: {
    ...DEFAULT_STYLES,
    textColor: '#ECFEFF',
    backgroundColor: '#0F172A',
    headerColor: '#164E63',
    borderColor: '#06B6D4',
    borderWidth: 1,
    cellPadding: 12,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  },
  candy: {
    ...DEFAULT_STYLES,
    textColor: '#701A75',
    backgroundColor: '#FCE7F3',
    headerColor: '#F5D0FE',
    borderColor: '#D946EF',
    borderWidth: 2,
    cellPadding: 14,
    stripedRows: true,
    hoverEffects: true,
    roundedCorners: true,
  },
  retro: {
    ...DEFAULT_STYLES,
    fontFamily: 'Courier New',
    fontSize: 13,
    textColor: '#1E293B',
    backgroundColor: '#F8FAFC',
    headerColor: '#BFDBFE',
    borderColor: '#60A5FA',
    borderWidth: 2,
    cellPadding: 14,
    stripedRows: true,
    hoverEffects: false,
    roundedCorners: false,
  },
  elegant: {
    ...DEFAULT_STYLES,
    fontFamily: 'Georgia',
    textColor: '#0F172A',
    backgroundColor: '#FFFFFF',
    headerColor: '#F1F5F9',
    borderColor: '#94A3B8',
    borderWidth: 1,
    borderStyle: 'solid',
    cellPadding: 14,
    stripedRows: false,
    hoverEffects: true,
    roundedCorners: true,
  }
};
